### ISSUE TITLE
Some minor enhancements in server.ts workflow

### ISSUE THREAD

**Issue by tmibvishal** [arpit-saxena/SenData#1]
**Note:** _This is just an enhancement_

**Line 223 server.ts**
```javascript
socket.on('CancelConnection',(user2_name: string) => {
```
Instead of receving the user2_name from the socket, directly find it from the user1 from which the socket request was send

**Line 102 server.ts**
Suppose user1 and user2 were connected but suddenly user2 gets disconnected
user2 will be broadcasted to all the other users in line 106
```javascript
//message to all other users also
socket.broadcast.emit('disconnect', disconnected_user);
```
But user1 is not broadcasted to everyone but now it is available

I might be wrong, so in that case, close the issue

**Comment by azztt** [comment]
Line 223 server.ts: made necessary changes

Line 102 server.ts: 
When user2 disconnected then the state of user1(user2's partner) is updated to idle. So when the user map is updated on the client side, user1 will automatically be available.
I don't its required to emit user1 from the server. So, I am closing the issue
